language: python
os:
  - osx
  - linux
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
matrix:
  fast_finish: true
  exclude:
    - os: "osx"
      python: "2.6"
notifications:
  email: false
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CONDA_OS='Linux'; else CONDA_OS='MacOSX'; fi;
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-${CONDA_OS}-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy
  - source activate test-environment
  - conda install scipy
  - pip install -r requirements_test.txt
  - python setup.py -q install
script:
  - python tests/test_doctests.py
  - py.test . -v --cov-report html --cov=fluids --cov-report term-missing 
after_success:
  - coveralls